### ISSUE TITLE
Set Current Game

### ISSUE THREAD

**Issue by ShadowRanger** [Vrekt/OriginXMPP#1]
The ability to set the Origin account's current game/status would be quite helpful.

**Comment by Vrekt** [comment]
This was planned but its bit weird to do. Usually you have the copy the presence packet directly from somebody else for it to work, as setting it myself with the code snippet below never works. (For Apex Legends anyways)

But you can always:
```java
final var presence = new Presence(Presence.Type.available, "Playing <X>", 0, Presence.Mode.available);
origin.connection().sendStanza(presence);
```

**Comment by ShadowRanger** [comment]
> This was planned but its bit weird to do. Usually you have the copy the presence packet directly from somebody else for it to work, as setting it myself with the code snippet below never works. (For Apex Legends anyways)
> 
> But you can always:
> 
> ```java
> final var presence = new Presence(Presence.Type.available, "Playing <X>", 0, Presence.Mode.available);
> origin.connection().sendStanza(presence);
> ```

Perfect, thank you.
