### ISSUE TITLE
Accept Friend Request Method

### ISSUE THREAD

**Issue by ShadowRanger** [Vrekt/OriginXMPP#2]
There is no **acceptFriendRequest** method, and the **sendFriendRequest** does not accept a friend request. Instead, it just sends a friend request to a user, even if there is a pending friend request from them.

**Comment by Vrekt** [comment]
Last time I tried it was not possible. There XMPP system is very weird and even replicating the same stanzas sent by a real client to accept a friend request it still would not work.

**Comment by ShadowRanger** [comment]
> Last time I tried it was not possible. There XMPP system is very weird and even replicating the same stanzas sent by a real client to accept a friend request it still would not work.

I have seen this done by an Origin bot before. I am not sure how they did it, but I definitely knew they could.

**Comment by Vrekt** [comment]
https://github.com/Vrekt/OriginXMPP/releases/tag/1.3
